title: "Putzbrunn Fraktur-Klassifikationen"
description: "Frakturklassifikationen, wie man sie in Putzbrunn verwendet"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
masthead_title: "Putzbrunn Klassifikationen"

plugins:
  - jekyll-include-cache

# Theme settings
minimal_mistakes_skin: "default"
locale: "en-GB"

# Navigation
sidebar:
  show_avatar: true
breadcrumbs: true

# Optional Google Fonts and SEO
author:
  name: "Putzbrunn Crew"
  avatar: "/assets/images/putzbrunn-ortsschild-blass-250px.png"

# Enable custom styles
sass:
  style: compressed
  
# Header
header:
  overlay_image: /assets/images/header-berge-bw-advanced.jpg
  show_overlay_excerpt: false